name = "studycod-ai-worker"
main = "src/index.ts"
compatibility_date = "2025-12-24"

[vars]
ENVIRONMENT = "development"

[env.production]
ai = { binding = "AI" }

[env.production.vars]
ENVIRONMENT = "production"
